export interface EventInfo {
  name: string;
  category: string;
  type: "Study" | "Lab" | "Build";
  icon: string;
  short: string;
  long: string;
}

/**
 * Shared descriptions for each event, keyed by canonical name.
 * Science Olympiad groups events into these science categories.
 */
export const EVENT_INFO: Record<string, EventInfo> = {
  "Anatomy & Physiology": {
    name: "Anatomy & Physiology",
    category: "Life & Personal Science",
    type: "Study",
    icon: "🫀",
    short:
      "Human body systems — for the current series the focus is the nervous, special senses, and endocrine systems.",
    long: "Students are assessed on the anatomy and physiology of selected human body systems. The rotating topic focus changes each season; recent series emphasize the nervous system, special senses (vision, hearing, taste, smell), and the endocrine system. Expect diagrams, case studies, and clinical applications.",
  },
  Astronomy: {
    name: "Astronomy",
    category: "Earth & Space Science",
    type: "Study",
    icon: "🔭",
    short:
      "Stellar astrophysics — star formation, stellar evolution, galaxies, and the use of image-analysis tools (DS9).",
    long: "Astronomy covers stellar evolution, the H-R diagram, binary and variable stars, galaxies, cosmology, and deep-space objects. Students analyze real astronomical images and data, often using the DS9 image viewer, and answer quantitative problems involving luminosity, distance modulus, and spectral classification.",
  },
  "Air Trajectory": {
    name: "Air Trajectory",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🎯",
    short:
      "Design a device that uses air pressure to launch projectiles at layered targets.",
    long: "Teams build a device that uses the force of a falling mass to propel a projectile (like a ball) through the air to hit a target at one of several distances. Scoring rewards accuracy and consistency across distance ranges.",
  },
  "Boomilever": {
    name: "Boomilever",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🏗️",
    short:
      "Build a cantilevered structure that supports a load as far from a wall as possible.",
    long: "Teams design and build a lightweight cantilevered beam or truss attached to a vertical wall that holds a load at a set distance. The score combines structural efficiency (load held divided by mass) with a load-scored bonus.",
  },
  Bridge: {
    name: "Bridge",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🌉",
    short: "Build a lightweight bridge that supports a maximum load.",
    long: "Teams construct a bridge of given span from wood and glue that supports a load applied to the center. The goal is maximum structural efficiency — the greatest load-to-mass ratio.",
  },
  "Bungee Drop": {
    name: "Bungee Drop",
    category: "Earth & Space Science",
    type: "Build",
    icon: "🪢",
    short:
      "Drop a mass on an elastic cord to stop as close to a target level as possible.",
    long: "Teams use an elastic cord to drop a mass from a height so that it decelerates and stops as close as possible to a target distance above the floor, modeling the physics of energy conservation and Hooke's law without touching the floor.",
  },
  "Circuit Lab": {
    name: "Circuit Lab",
    category: "Physical Science & Chemistry",
    type: "Lab",
    icon: "🔌",
    short: "Electricity and magnetism — circuits, components, and measurement.",
    long: "Circuit Lab covers DC circuit analysis (Ohm's and Kirchhoff's laws), series and parallel networks, capacitors, magnetism, and electromagnetism. The lab portion includes building and measuring circuits and interpreting meter readings.",
  },
  "Chemistry Lab": {
    name: "Chemistry Lab",
    category: "Physical Science & Chemistry",
    type: "Lab",
    icon: "🧪",
    short:
      "General and physical chemistry with hands-on wet-lab tasks and data analysis.",
    long: "Chemistry Lab tests chemistry knowledge with a rotating focus (e.g., acids & bases, gases, kinetics, thermodynamics) plus an on-site lab component. Students perform titrations and measurements and analyze quantitative data.",
  },
  "Potions and Poisons": {
    name: "Potions and Poisons",
    category: "Physical Science & Chemistry",
    type: "Lab",
    icon: "☠️",
    short:
      "Chemical properties and effects of household and environmental toxins.",
    long: "This Division B event focuses on the chemical properties and physiological effects of selected toxic and therapeutic substances, emphasizing common household and environmental poisons, identification tests, and dose-response concepts.",
  },
  Codebusters: {
    name: "Codebusters",
    category: "Inquiry & Nature of Science",
    type: "Study",
    icon: "🔐",
    short: "Cryptanalysis — decode historical and modern ciphers against the clock.",
    long: "Teams cryptanalyze and decode encrypted messages using a variety of ciphers, including Caesar, Vigenère, affine, RSA basics, and the Hill cipher. The event includes timed decryption and a constructed-response 'question' the team must encode for grading.",
  },
  "Crime Busters": {
    name: "Crime Busters",
    category: "Inquiry & Nature of Science",
    type: "Lab",
    icon: "🕵️",
    short:
      "Identify mystery powders, liquids, metals, and fibers to solve a crime.",
    long: "Given a scenario and evidence, Division B students perform chemical and physical tests to identify unknown powders, liquids, metals, and fibers, then use the results and witness statements to solve a crime.",
  },
  "Designer Genes": {
    name: "Designer Genes",
    category: "Life & Personal Science",
    type: "Study",
    icon: "🧬",
    short:
      "Molecular and classical genetics — DNA, heredity, biotechnology (Division C).",
    long: "Designer Genes covers molecular and Mendelian genetics, DNA structure and replication, transcription and translation, gene regulation, biotechnology (PCR, CRISPR, gel electrophoresis), and population genetics. Problems include pedigrees, dihybrid crosses, and gene expression analysis.",
  },
  Heredity: {
    name: "Heredity",
    category: "Life & Personal Science",
    type: "Study",
    icon: "🧬",
    short: "Classical and molecular genetics for Division B.",
    long: "Heredity is the Division B genetics event, covering Mendelian inheritance, Punnett squares, probability, pedigrees, meiosis, and an introduction to DNA and molecular genetics.",
  },
  "Disease Detectives": {
    name: "Disease Detectives",
    category: "Inquiry & Nature of Science",
    type: "Study",
    icon: "🦠",
    short: "Epidemiology — investigate disease outbreaks in populations.",
    long: "Disease Detectives applies epidemiological methods to study disease, injury, and health in populations. Students calculate and interpret rates (incidence, prevalence, attack rates), design case-control and cohort studies, and work through outbreak investigations with a rotating topic focus.",
  },
  "Dynamic Planet": {
    name: "Dynamic Planet",
    category: "Earth & Space Science",
    type: "Study",
    icon: "🌍",
    short:
      "Earth systems with a rotating focus (e.g., cryosphere, oceanography, tectonics).",
    long: "Dynamic Planet covers large-scale Earth processes with a rotating annual topic — recently the cryosphere (glaciers, sea ice, permafrost) and oceanography. Students interpret maps, cross-sections, and data about Earth's dynamic systems.",
  },
  "Electric Vehicle": {
    name: "Electric Vehicle",
    category: "Technology & Engineering",
    type: "Build",
    icon: "⚡",
    short: "Build a battery-powered vehicle that stops precisely at a target distance.",
    long: "Teams design and build a vehicle powered by electricity that travels a distance announced at the competition and stops as close as possible to the target, with scoring based on accuracy and time.",
  },
  "Engineering CAD": {
    name: "Engineering CAD",
    category: "Technology & Engineering",
    type: "Build",
    icon: "📐",
    short: "Computer-aided design — model parts and assemblies to specification.",
    long: "Engineering CAD assesses the ability to create accurate 3D computer-aided design models from given specifications, including part modeling, assemblies, and technical drawing interpretation.",
  },
  "Write It Do It": {
    name: "Write It Do It",
    category: "Inquiry & Nature of Science",
    type: "Build",
    icon: "✍️",
    short:
      "One partner writes instructions; the other rebuilds the object sight-unseen.",
    long: "A communication event: one team member (the 'writer') views an object and writes instructions to build it, while the other (the 'doer') uses only those instructions to reconstruct it. Scoring rewards fidelity to the original.",
  },
  Entomology: {
    name: "Entomology",
    category: "Life & Personal Science",
    type: "Study",
    icon: "🐛",
    short: "Identify insects by order and family and answer insect-biology questions.",
    long: "Students identify insects (and selected immatures) to order and family, construct and use dichotomous keys, and answer questions about insect anatomy, life cycles, behavior, and ecology. The official insect list spans dozens of families.",
  },
  "Experimental Design": {
    name: "Experimental Design",
    category: "Inquiry & Nature of Science",
    type: "Lab",
    icon: "🔬",
    short: "Design, run, and write up a controlled experiment entirely on-site.",
    long: "Given a set of materials and a prompt, students design and conduct a controlled experiment, then write a formal lab report covering hypothesis, variables, procedure, data tables, graphs, statistics, and a conclusion with error analysis.",
  },
  Forensics: {
    name: "Forensics",
    category: "Inquiry & Nature of Science",
    type: "Lab",
    icon: "🔍",
    short: "Apply chemistry, biology, and physics evidence to solve a crime (Division C).",
    long: "Forensics gives teams a crime scenario and physical evidence — polymers, powders, metals, hair, fibers, fingerprints, chromatography, and blood spatter — plus witness statements, to identify suspects and reconstruct events.",
  },
  Forestry: {
    name: "Forestry",
    category: "Life & Personal Science",
    type: "Study",
    icon: "🌲",
    short: "Identify trees and understand forest ecology and management.",
    long: "Students identify trees from an official list using leaves, bark, fruit, and form, and answer questions about tree biology, forest ecology, succession, and forestry management.",
  },
  Helicopter: {
    name: "Helicopter",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🚁",
    short: "Build a rubber-powered helicopter for maximum flight time.",
    long: "Teams construct a rubber-band-powered free-flight helicopter and optimize it for maximum time aloft, balancing rotor design, weight, and rubber motor winding.",
  },
  Flight: {
    name: "Flight",
    category: "Technology & Engineering",
    type: "Build",
    icon: "✈️",
    short: "Build a rubber-powered indoor airplane for maximum flight time.",
    long: "Flight (formerly Wright Stuff / Elastic Launched Glider) challenges teams to build a rubber-powered indoor monoplane that stays aloft as long as possible, applying aerodynamics, trim, and efficient energy storage.",
  },
  Hovercraft: {
    name: "Hovercraft",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🛸",
    short: "Build a self-propelled, air-levitated vehicle that navigates a track.",
    long: "Teams build and calibrate a self-propelled air-levitated hovercraft that travels down a track. The event combines a written test on fluid mechanics and motion with the device run.",
  },
  Machines: {
    name: "Machines",
    category: "Physical Science & Chemistry",
    type: "Lab",
    icon: "⚙️",
    short: "Simple and compound machines, plus a lever-based measuring device.",
    long: "Machines covers simple machines (lever, pulley, inclined plane, wedge, screw, wheel-and-axle), mechanical advantage, efficiency, and work. Teams also build a lever-based device to determine mass ratios.",
  },
  "Wind Power": {
    name: "Wind Power",
    category: "Technology & Engineering",
    type: "Build",
    icon: "💨",
    short: "Build a turbine blade assembly and answer energy-conversion questions.",
    long: "Wind Power combines a written test on wind energy, power, and fluid dynamics with a device component in which teams build and test a blade/turbine assembly to maximize electrical output, plus a written portion on alternative energy.",
  },
  "Materials Science": {
    name: "Materials Science",
    category: "Physical Science & Chemistry",
    type: "Study",
    icon: "🧱",
    short: "Properties, structure, and processing of metals, ceramics, polymers, composites.",
    long: "Materials Science covers the four classes of materials (metals, ceramics, polymers, composites), crystal structures, stress-strain behavior, phase diagrams, and material characterization techniques. Includes lab-style data analysis problems.",
  },
  "Microbe Mission": {
    name: "Microbe Mission",
    category: "Life & Personal Science",
    type: "Study",
    icon: "🦠",
    short: "Microbiology — bacteria, viruses, protists, and the human microbiome.",
    long: "Microbe Mission covers the diversity, structure, and function of microbes (bacteria, archaea, viruses, fungi, protists), microbial metabolism and growth, the immune response, disease, and environmental/industrial microbiology.",
  },
  Optics: {
    name: "Optics",
    category: "Physical Science & Chemistry",
    type: "Lab",
    icon: "👁️",
    short: "Geometric and physical optics plus a laser-shoot barrier challenge.",
    long: "Optics covers reflection, refraction, lenses, mirrors, wave optics, and the electromagnetic spectrum. The lab component includes a laser 'shoot' where teams position mirrors to hit a target around a barrier.",
  },
  "Remote Sensing": {
    name: "Remote Sensing",
    category: "Earth & Space Science",
    type: "Study",
    icon: "🛰️",
    short: "Interpret satellite imagery and data to analyze Earth systems.",
    long: "Remote Sensing tests understanding of how sensors on satellites and aircraft collect data, and the ability to interpret imagery, multispectral bands, maps, and datasets to study Earth's surface, atmosphere, and oceans.",
  },
  "Robot Tour": {
    name: "Robot Tour",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🤖",
    short: "Build and program an autonomous robot to navigate a course.",
    long: "Teams design, build, and program an autonomous robot to traverse a course, score points by visiting checkpoints and performing tasks, demonstrating integration of mechanical design and sensor-based programming.",
  },
  "Rocks and Minerals": {
    name: "Rocks and Minerals",
    category: "Earth & Space Science",
    type: "Study",
    icon: "🪨",
    short: "Identify rocks and minerals and interpret their geologic significance.",
    long: "Students identify specimens from an official list of rocks and minerals using properties like hardness, streak, luster, cleavage, and reaction to acid, and answer questions about formation environments and geologic processes.",
  },
  Fossils: {
    name: "Fossils",
    category: "Earth & Space Science",
    type: "Study",
    icon: "🦴",
    short: "Identify fossils and interpret ancient life and environments.",
    long: "Fossils covers identifying specimens from an official fossil list (by genus/specimen and geologic period), plus understanding modes of preservation, paleoecology, evolution, and using the geologic time scale.",
  },
  "Water Quality": {
    name: "Water Quality",
    category: "Life & Personal Science",
    type: "Study",
    icon: "💧",
    short: "Assess freshwater aquatic environments and their macroinvertebrates.",
    long: "Water Quality assesses understanding of freshwater ecosystems, the water cycle, parameters like dissolved oxygen, turbidity, and pH, pollution, and the identification and tolerance classification of aquatic macroinvertebrates as water-quality indicators.",
  },
  Ecology: {
    name: "Ecology",
    category: "Life & Personal Science",
    type: "Study",
    icon: "🌿",
    short: "Ecosystems, energy flow, nutrient cycles, and population dynamics.",
    long: "Ecology covers ecosystem structure, food webs and energy flow, biogeochemical cycles, population dynamics, succession, biodiversity, and conservation, with a rotating biome focus (e.g., grasslands, deserts, tundra).",
  },
  Meteorology: {
    name: "Meteorology",
    category: "Earth & Space Science",
    type: "Study",
    icon: "⛅",
    short: "Weather and climate — interpret data, maps, and climate change.",
    long: "Meteorology covers the factors that influence weather and climate, atmospheric structure, pressure and wind systems, fronts, severe weather, and climate change, with emphasis on interpreting climatological data and maps.",
  },
  "Metric Mastery": {
    name: "Metric Mastery",
    category: "Inquiry & Nature of Science",
    type: "Lab",
    icon: "📏",
    short: "Estimate, measure, and convert metric quantities accurately.",
    long: "Metric Mastery tests the ability to estimate and then precisely measure properties (mass, volume, area, density, force, distance, time, temperature) of objects, and to perform metric unit conversions and significant-figure reasoning.",
  },
  "Mission Possible": {
    name: "Mission Possible",
    category: "Technology & Engineering",
    type: "Build",
    icon: "⛓️",
    short: "Build a Rube Goldberg device that chains actions to a final task.",
    long: "Teams design and document a Rube Goldberg-style device that completes a start action and a final action through a series of specified energy transfers, scoring on successful operation, unique actions, and the technical log.",
  },
  Scrambler: {
    name: "Scrambler",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🥚",
    short: "Use a falling mass to launch a vehicle carrying an egg to a barrier.",
    long: "Teams build a device that uses the energy of a falling mass to transport an egg along a track as quickly as possible and stop near a barrier without breaking the egg, trading off speed and precision.",
  },
  "Solar System": {
    name: "Solar System",
    category: "Earth & Space Science",
    type: "Study",
    icon: "🪐",
    short: "Planet formation and structure within and beyond the Solar System (Division B).",
    long: "Solar System is the Division B astronomy event, covering planet formation, the structure of the Sun and planets, moons, asteroids, comets, exoplanets, and small bodies, often with a rotating focus body or region.",
  },
  "Reach for the Stars": {
    name: "Reach for the Stars",
    category: "Earth & Space Science",
    type: "Study",
    icon: "⭐",
    short: "Stars, galaxies, and observational astronomy for Division B.",
    long: "Reach for the Stars introduces Division B students to the properties of stars, constellations, galaxies, and deep-space objects, and the use of star maps and the H-R diagram.",
  },
  "Gravity Vehicle": {
    name: "Gravity Vehicle",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🛷",
    short: "A ramp-launched vehicle that travels a set distance and stops accurately.",
    long: "Gravity Vehicle teams build a vehicle powered only by gravity (launched from a ramp) that travels a specified distance as fast as possible and stops close to a target line.",
  },
  "Geologic Mapping": {
    name: "Geologic Mapping",
    category: "Earth & Space Science",
    type: "Study",
    icon: "🗺️",
    short: "Read and construct geologic maps, cross-sections, and structure data.",
    long: "Geologic Mapping tests interpretation of topographic and geologic maps, stratigraphy, strike and dip, folds and faults, unconformities, and the construction of geologic cross-sections and block diagrams.",
  },
  "Bio Process Lab": {
    name: "Bio Process Lab",
    category: "Life & Personal Science",
    type: "Lab",
    icon: "🧫",
    short: "Use lab skills and scientific process to answer biology questions (Division B).",
    long: "Bio Process Lab assesses the ability to use science process skills — observing, measuring, estimating, using tools and techniques — to solve biology problems and interpret data on-site.",
  },
  "Roller Coaster": {
    name: "Roller Coaster",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🎢",
    short: "Build a marble track that maximizes run time with a single starting hill.",
    long: "Teams construct a track along which a standard marble travels, with scoring based on maximizing the total run time using energy conservation, friction control, and creative track design.",
  },
  "Storm the Castle": {
    name: "Storm the Castle",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🏰",
    short: "Build a counterweight trebuchet to hit targets at range.",
    long: "Teams design and build a counterweight trebuchet to accurately launch projectiles at targets at known and unknown distances, applying projectile motion and energy-transfer principles.",
  },
  "Wheeled Vehicle": {
    name: "Wheeled Vehicle",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🛞",
    short: "A vehicle that travels a set distance and stops on target.",
    long: "Wheeled Vehicle teams build a vehicle (often powered by a non-electric source) that travels a specified distance and stops as close as possible to a target line, with scoring on distance accuracy and run time.",
  },
  "Road Scholar": {
    name: "Road Scholar",
    category: "Earth & Space Science",
    type: "Study",
    icon: "🧭",
    short: "Interpret and create maps — topographic, road, and satellite (Division B).",
    long: "Road Scholar tests map-reading skills: interpreting topographic, highway, and satellite maps; using scale, contour lines, latitude/longitude, magnetic declination, and drawing map profiles.",
  },
  "Tower": {
    name: "Tower",
    category: "Technology & Engineering",
    type: "Build",
    icon: "🗼",
    short: "Build a tower that supports a load for maximum efficiency.",
    long: "Teams build a tower of given height that supports a load applied at the top, aiming for maximum structural efficiency — the largest load-to-mass ratio while meeting geometric constraints.",
  },
  "Can't Judge a Powder": {
    name: "Can't Judge a Powder",
    category: "Physical Science & Chemistry",
    type: "Lab",
    icon: "⚗️",
    short: "Determine the physical and chemical properties of an unknown powder.",
    long: "Students are given a white powder and perform a series of observational and chemical tests to determine its physical and chemical properties — without identifying the specific substance, only characterizing it.",
  },
  Botany: {
    name: "Botany",
    category: "Life & Personal Science",
    type: "Study",
    icon: "🌱",
    short: "Plant biology — identification, anatomy, physiology, and diversity (trial).",
    long: "Botany covers plant anatomy, physiology, reproduction, classification, and diversity. Offered as a trial/event at some tournaments; students identify plants and answer questions about plant biology.",
  },
};

export type Slate = {
  season: "2025" | "2026" | "2027";
  division: "B" | "C";
  projected?: boolean;
  events: string[];
};

export const SEASON_SLATES: Slate[] = [
  // ---- 2025 season (previous 2024-25 series) ----
  {
    season: "2025",
    division: "B",
    events: [
      "Anatomy & Physiology",
      "Bio Process Lab",
      "Codebusters",
      "Crime Busters",
      "Disease Detectives",
      "Dynamic Planet",
      "Ecology",
      "Experimental Design",
      "Fossils",
      "Meteorology",
      "Microbe Mission",
      "Optics",
      "Roller Coaster",
      "Road Scholar",
      "Solar System",
      "Storm the Castle",
      "Wheeled Vehicle",
      "Wind Power",
      "Write It Do It",
      "Heredity",
      "Can't Judge a Powder",
    ],
  },
  {
    season: "2025",
    division: "C",
    events: [
      "Anatomy & Physiology",
      "Astronomy",
      "Chemistry Lab",
      "Codebusters",
      "Disease Detectives",
      "Dynamic Planet",
      "Ecology",
      "Entomology",
      "Experimental Design",
      "Flight",
      "Forensics",
      "Forestry",
      "Geologic Mapping",
      "Gravity Vehicle",
      "Materials Science",
      "Microbe Mission",
      "Optics",
      "Robot Tour",
      "Rocks and Minerals",
      "Scrambler",
      "Tower",
      "Wind Power",
      "Write It Do It",
    ],
  },

  // ---- 2026 season (CURRENT 2025-26 series) ----
  {
    season: "2026",
    division: "B",
    events: [
      "Anatomy & Physiology",
      "Boomilever",
      "Circuit Lab",
      "Codebusters",
      "Crime Busters",
      "Disease Detectives",
      "Dynamic Planet",
      "Entomology",
      "Experimental Design",
      "Helicopter",
      "Heredity",
      "Hovercraft",
      "Machines",
      "Meteorology",
      "Metric Mastery",
      "Mission Possible",
      "Potions and Poisons",
      "Remote Sensing",
      "Rocks and Minerals",
      "Scrambler",
      "Solar System",
      "Water Quality",
      "Write It Do It",
    ],
  },
  {
    season: "2026",
    division: "C",
    events: [
      "Anatomy & Physiology",
      "Astronomy",
      "Boomilever",
      "Bungee Drop",
      "Chemistry Lab",
      "Circuit Lab",
      "Codebusters",
      "Designer Genes",
      "Disease Detectives",
      "Dynamic Planet",
      "Electric Vehicle",
      "Engineering CAD",
      "Entomology",
      "Ecology",
      "Experimental Design",
      "Forensics",
      "Fossils",
      "Geologic Mapping",
      "Helicopter",
      "Hovercraft",
      "Materials Science",
      "Microbe Mission",
      "Optics",
      "Remote Sensing",
      "Robot Tour",
      "Rocks and Minerals",
      "Water Quality",
      "Wind Power",
      "Write It Do It",
    ],
  },

  // ---- 2027 season (PROJECTED next-year series) ----
  {
    season: "2027",
    division: "B",
    projected: true,
    events: [
      "Anatomy & Physiology",
      "Botany",
      "Bridge",
      "Codebusters",
      "Crime Busters",
      "Disease Detectives",
      "Dynamic Planet",
      "Ecology",
      "Entomology",
      "Experimental Design",
      "Flight",
      "Heredity",
      "Meteorology",
      "Microbe Mission",
      "Mission Possible",
      "Optics",
      "Potions and Poisons",
      "Reach for the Stars",
      "Road Scholar",
      "Rocks and Minerals",
      "Solar System",
      "Water Quality",
      "Write It Do It",
    ],
  },
  {
    season: "2027",
    division: "C",
    projected: true,
    events: [
      "Anatomy & Physiology",
      "Astronomy",
      "Bridge",
      "Chemistry Lab",
      "Circuit Lab",
      "Codebusters",
      "Designer Genes",
      "Disease Detectives",
      "Dynamic Planet",
      "Ecology",
      "Entomology",
      "Experimental Design",
      "Forensics",
      "Fossils",
      "Geologic Mapping",
      "Gravity Vehicle",
      "Materials Science",
      "Microbe Mission",
      "Optics",
      "Remote Sensing",
      "Robot Tour",
      "Rocks and Minerals",
      "Scrambler",
      "Tower",
      "Wind Power",
      "Write It Do It",
    ],
  },
];

export function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export const DEFAULT_SOURCE =
  "Curated in the style of Science Olympiad invitational practice tests & official rules manuals";
